<?xml version="1.0"?>
<robot name ="biped" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 
    Properties
  -->
  <xacro:property name = "torso_width" value = "0.1"/>
  <xacro:property name = "torso_height" value = "0.15"/>
  <xacro:property name = "torso_depth" value = "0.05"/>
  <xacro:property name = "torso_mass" value = "0.2"/>


  <xacro:property name = "foot_width" value = "0.05"/>
  <xacro:property name = "foot_height" value = "0.005"/>
  <xacro:property name = "foot_length" value = "0.1000"/>
  <xacro:property name = "foot_mass" value = "10"/>

  <xacro:property name = "lower_leg_width" value = "0.01"/>
  <xacro:property name = "lower_leg_height" value = "0.02"/>
  <xacro:property name = "lower_leg_length" value = "0.20"/>
  <xacro:property name = "lower_leg_mass" value = "0.10"/>

  <xacro:property name = "upper_leg_width" value = "0.01"/>
  <xacro:property name = "upper_leg_height" value = "0.02"/>
  <xacro:property name = "upper_leg_length" value = "0.20"/>
  <xacro:property name = "upper_leg_mass" value = "0.10"/>

<!--
  Motor based on RMD-L-4015
  http://www.gyems.cn/794904.html
-->
  <xacro:property name = "motor_length" value = "0.033"/>
  <xacro:property name = "motor_radius" value = "0.0198"/>
  <xacro:property name = "motor_mass" value = "0.120"/>
  <xacro:property name = "motor_torque_nm" value = "2.49"/> <!-- stall torque 0.49 , nominal is 0.22 -->

  <xacro:property name = "color_red" value = "1 0 0 1"/>
  <xacro:property name = "color_gold" value = "0.831 0.686 0.216 1"/>
  <xacro:property name = "color_dark_grey" value = "0.4 0.4 0.4 1"/>

  <!-- 
    Macros 
  -->
  <xacro:macro name="box_link" params="name m x y z origin:='0 0 0' rpy:='0 0 0' color">
    <link name = "${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="${rpy}"/>
        <mass value="${m}"/>
        <inertia ixx = "${m/12*(y*y+z*z)}" ixy = "0.0" ixz="0.0" iyy="${m/12*(x*x+z*z)}" iyz="0.0" izz="${m/12*(x*x+y*y)}"/>
      </inertial>
      <visual>
        <origin xyz="${origin}" rpy="${rpy}"/>
        <geometry>
          <box size="${x} ${y} ${z}" />
        </geometry>
        <material name="${name}_material">
          <color rgba = "${color}"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${origin}" rpy="${rpy}"/>
        <geometry>
          <box size="${x} ${y} ${z}" />
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="cylinder_link" params="name r l m color origin:='0 0 0' rpy:='0 0 0' ">
    <link name="${name}">
      <inertial>
        <origin xyz="${origin}" rpy="${rpy}" />
        <mass value="${m}"/>
        <inertia ixx="${m*r*r/4+m*l*l}" ixy="0" ixz="0" iyy="${m*r*r/4+m*l*l}" iyz="0" izz="${m*r*r/2}" />
      </inertial>

      <visual>
        <origin xyz="${origin}" rpy="${rpy}" />
        <geometry>
          <cylinder radius="${r}" length="${l}"/>
        </geometry>
        <material name="${name}_color">
          <color rgba="${color}"/>
        </material>
      </visual>

      <collision>
        <origin xyz="${origin}" rpy="${rpy}" />
        <geometry>
          <cylinder radius="${r}" length="${l}"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <!-- 
    Links
  -->
  <link name="base_link"></link>
  <xacro:box_link name="torso" x="${torso_depth}" y="${torso_width}" z="${torso_height}" m = "${torso_mass}" origin="0 0 ${-torso_height/2}" rpy="0 0 0.0" color = "${color_dark_grey}"/>
  <xacro:cylinder_link name="left_hip_motor" m="${motor_mass}" r="${motor_radius}" l="${motor_length}" rpy="${pi/2} 0 0" color="${color_dark_grey}"/>
  <xacro:box_link name="upper_left_leg" x="${upper_leg_length}" y="${upper_leg_height}" z="${upper_leg_width}" m = "${upper_leg_mass}" origin="0 0 ${-upper_leg_length/2}" rpy="0 ${-pi/2} 0.0" color = "${color_red}"/>
  <xacro:cylinder_link name="left_knee_motor" m="${motor_mass}" r="${motor_radius}" l="${motor_length}" rpy="${pi/2} 0 0" color="${color_dark_grey}"/>
  <xacro:box_link name="lower_left_leg" x="${lower_leg_length}" y="${lower_leg_height}" z="${lower_leg_width}" m = "${lower_leg_mass}" origin="0 0 ${-lower_leg_length/2}" rpy="0 ${-pi/2} 0.0" color = "${color_gold}"/>
  <xacro:cylinder_link name="left_ankle_motor" m="${motor_mass}" r="${motor_radius}" l="${motor_length}" rpy="${pi/2} 0 0" color="${color_dark_grey}"/>
  <xacro:box_link name="left_foot" x="${foot_length}" y="${foot_width}" z="${foot_height}" m = "${foot_mass}" origin="0 0 ${-motor_radius -foot_height/2}" rpy="0 0.0 0.0" color = "${color_gold}"/>

  <!-- 
    Joints
  -->
  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="torso"/>
  </joint>

  <joint name="torso_to_left_hip_motor_joint" type="fixed">
    <parent link="torso"/>
    <origin xyz="0 ${-torso_width/2} ${-torso_height}" rpy="0 0 0"/>
    <child link="left_hip_motor"/>
  </joint>

  <joint name = "left_hip" type = "revolute">
    <axis xyz="0 1 0"/>
    <limit effort="${motor_torque_nm}" lower="${-2*pi}" upper="${2*pi}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="left_hip_motor"/>
    <child link="upper_left_leg"/>
  </joint>

  <joint name="upper_left_leg_to_knee_motor_joint" type="fixed">
    <parent link="upper_left_leg"/>
    <origin xyz="0 0 ${-upper_leg_length}" rpy="0 0 0"/>
    <child link="left_knee_motor"/>
  </joint>

  <joint name = "left_knee" type = "revolute">
    <axis xyz="0 1 0"/>
    <limit effort="${motor_torque_nm}" lower="${-2*pi}" upper="${2*pi}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="left_knee_motor"/>
    <child link="lower_left_leg"/>
  </joint>

  <joint name = "lower_left_leg_to_ankle_motor" type="fixed">
    <parent link = "lower_left_leg"/>
    <child link = "left_ankle_motor"/>
    <origin xyz="0 0 ${-lower_leg_length} "/>
  </joint>

  <joint name = "left_ankle" type = "revolute">
    <axis xyz="0 1 0"/>
    <limit effort="${motor_torque_nm*3}" lower="${-2*pi}" upper="${2*pi}" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="left_ankle_motor"/>
    <child link="left_foot"/>
  </joint>

  <!--
    Gazebo colors from
    https://github.com/osrf/gazebo/blob/master/media/materials/scripts/gazebo.material
  -->
  <gazebo reference="left_foot">
    <material>Gazebo/RedTransparent</material>
  </gazebo>

  <gazebo reference="lower_left_leg">
    <material>Gazebo/Gold</material>
  </gazebo>

  <gazebo reference="upper_left_leg">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_knee_motor">
    <material>Gazebo/DarkGray</material>
  </gazebo>

  <gazebo reference="left_ankle_motor">
    <material>Gazebo/DarkGray</material>
  </gazebo>

  <gazebo reference="left_hip_motor">
    <material>Gazebo/DarkGray</material>
  </gazebo>

  <gazebo reference="torso">
    <material>Gazebo/Gold</material>
  </gazebo>


  <!--
    Gazebo ros control
  -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/biped</robotNamespace>
    </plugin>
  </gazebo>

  <!-- 
    Transmissions for robot control
  -->
  <transmission name="left_ankle_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_ankle">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_ankle_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>3</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_knee_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_knee">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_knee_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_hip_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_hip">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_hip_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
